// <auto-generated />
using System;
using ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20240129132730_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Post identifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Post content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Post title");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e362a84-3b22-4401-bfae-0854f03af75d"),
                            Content = "Firste sit amet faucibus velit, in facilisis neque. Quisque posuere ex quis tincidunt porta. Curabitur.\r\n\r\n",
                            Title = "First Post"
                        },
                        new
                        {
                            Id = new Guid("628dac58-8f86-4ee2-b77d-363141780481"),
                            Content = "Seconde sit amet faucibus velit, in facilisis neque. Quisque posuere ex quis tincidunt porta. Curabitur.\r\n\r\n",
                            Title = "Second Post"
                        },
                        new
                        {
                            Id = new Guid("946d7890-7dee-47f9-a1f6-36bc2f603fcf"),
                            Content = "Thirde sit amet faucibus velit, in facilisis neque. Quisque posuere ex quis tincidunt porta. Curabitur.\r\n\r\n",
                            Title = "Third Post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
